version: '3'

services:
  config-server:
    build:
      context: ./config-server
      dockerfile: ./Dockerfile
    ports:
      - "8888:8888"
  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: ./Dockerfile
    ports:
      - "8761:8761"