spring:
  application:
    name: payment-service
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:payment-db
    username: sa
    password:
    driverClassName: org.h2.Driver

server:
  port: 0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id : ${spring.application.name}:${spring.application.instance_id:${random.value}}
